### PR TITLE
take *all* Python lib dirs into account in PythonPackage easyblock

### PR DESCRIPTION
**Pull request by boegel**
required for https://github.com/hpcugent/easybuild-easyconfigs/pull/1692

requires https://github.com/hpcugent/easybuild-framework/pull/1300

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
looks fine  I think

**Comment by boegel** [comment]
https://github.com/hpcugent/easybuild-framework/pull/1300 is required for this to work correctly

**Comment by boegel** [comment]
I've (re)tested several Python packages on top of this, combined with https://github.com/hpcugent/easybuild-framework/pull/1300 (which is merged in).

So: going in, thanks for the review @wpoely86!

**Pull request merged**
