### PR TITLE
New EasyBlock for IMOD visualisation software

### PR DESCRIPTION
**Pull request by valtandor**

### CODE REVIEW

**Comment by valtandor** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@valtandor please review/merge https://github.com/valtandor/easybuild-easyblocks/pull/3

**Comment by boegel** [comment]
tested with https://github.com/hpcugent/easybuild-easyconfigs/pull/1187, good to go

Thanks @valtandor!

**Pull request merged**
