### PR TITLE
only restore $PYTHONPATH if it was defined

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by JensTimmerman** [comment]
can we have a test for this?

**Comment by JensTimmerman** [comment]
wouldn't it not make sense to have some unittests for the generic EasyBlocks?

**Comment by boegel** [comment]
@JensTimmerman: you mean like, creating small toy programs that are built using the generic easyblocks? it can get tricky expensive, for example if CMake is involved, or for OCamlPackage, etc...

We should do proper testing with the actual applications instead when updating easyblocks (which I typically do when an existing easyblock is touched).

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
looks good

**Comment by boegel** [comment]
Thanks @wpoely86!

**Pull request merged**
