### PR TITLE
implement runtime patching of $WM_* and compiler variables for OpenFOAM

### PR DESCRIPTION
**Pull request by boegel**
This implements the fix that was proposed by @wpoely86 as an alternative to https://github.com/hpcugent/easybuild-easyconfigs/pull/1920 .

It fixes https://github.com/hpcugent/easybuild-easyconfigs/issues/1842, and also makes one of the required patch file quite a bit smaller (cfr. https://github.com/hpcugent/easybuild-easyconfigs/pull/1968).

### CODE REVIEW

**Comment by boegel** [comment]
cc @FokkeDijkstra

**Comment by boegel** [comment]
@JensTimmerman: please review

**Comment by JensTimmerman** [comment]
ok

**Comment by boegel** [comment]
Thanks for the review @JensTimmerman!

I'll make sure this doesn't break any of the existing OpenFOAM builds before I merge it in...

**Comment by boegel** [comment]
Some more shuffling around was needed to make sure that the extra compiler flags were injected as well, all OpenFOAM and OpenFOAM-Extend builds now still work.

Going in, thanks for the review @JensTimmerman!

**Pull request merged**
