### PR TITLE
update PGI easyblock to install siterc file so PGI picks up $LIBRARY_PATH + enhance sanity check paths for compiler commands

### PR DESCRIPTION
**Pull request by boegel**
fix for #918

cc @geimer, @damianam, @bartoldeman: please review?

### CODE REVIEW

**Comment by damianam** [comment]
It looks good to me but I think we should check if `siterc` is really honoured (just in case the documentation is not accurate, like with `PGI_JAVA`). We don't have siterc in our system, but we have a bunch of other rc files. I wonder if `siterc` got deprecated in favour of `localrc` or something like that.

**Comment by boegel** [comment]
@damianam works as advertised:

```
$ file $EBROOTPGI/linux86-64/16.3/bin/siterc
/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/PGI/16.3-GCC-4.9.3-2.25/linux86-64/16.3/bin/siterc

$ pgc++ -v hello.cpp 2>&1 | tr ' ' '\n' | grep '\-L'
-L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/PGI/16.3-GCC-4.9.3-2.25/linux86-64/16.3/lib
-L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/numactl/2.0.11-GCCcore-4.9.3/lib
-L/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/binutils/2.25-GCCcore-4.9.3/lib
-L/apps/gent/SL6/sandybridge/software/GCCcore/4.9.3/lib64
-L/apps/gent/SL6/sandybridge/software/GCCcore/4.9.3/lib
-L/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/PGI/16.3-GCC-4.9.3-2.25/linux86-64/16.3/lib
-L/usr/lib64
-L/vscmnt/gent_vulpix_apps/_apps_gent/SL6/sandybridge/software/GCCcore/4.9.3/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.3
-L/vscmnt/gent_vulpix_apps/_apps_gent/SL6/sandybridge/software/GCCcore/4.9.3/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib64
```

compare this without having the `siterc`:

```
$ ls $EBROOTPGI/linux86-64/16.3/bin/siterc
ls: cannot access /user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/PGI/16.3-GCC-4.9.3-2.25/linux86-64/16.3/bin/siterc: No such file or directory

$ pgc++ -v hello.cpp 2>&1 | tr ' ' '\n' | grep '\-L'
-L/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/PGI/16.3-GCC-4.9.3-2.25/linux86-64/16.3/lib
-L/usr/lib64
-L/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/GCCcore/4.9.3/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.3
-L/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_REGTEST/CO7/haswell-ib/software/GCCcore/4.9.3/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib64
```

**Comment by rjeschmi** [comment]
This is probably a good idea.

I think a lot of software that uses pgi works around it.

**Comment by geimer** [comment]
@boegel: lgtm, but...

To make it work on my Debian system, I need to add `/usr/lib/x86_64-linux-gnu` to `$LIBRARY_PATH`.  However, I can't simply add a `modextrapaths` line to the easyconfig file for this, as `modextrapaths` doesn't allow absolute paths... Is there any workaround or do we have to handle this in the easyblock as well?

**Comment by boegel** [comment]
@geimer ah right, I forgot about that part...

There's some discussion on making `modextrapaths` accept absolute paths too, but I still think it would be better to handle this for PGI specifically in the `siterc` file being added by the easyblock.

Can you verify whether adding this in the `siterc` as well fixes the problem?

```
# also include the location where libm & co live on Debian-based systems
append LDLIBARGS=/usr/lib/x86_64-linux-gnu;
```

Do we need to worry about `lib64` too here?

**Comment by boegel** [comment]
@geimer actually, I think it should be this (i.e. include the `-L`)

```
# also include the location where libm & co live on Debian-based systems
append LDLIBARGS=-L/usr/lib/x86_64-linux-gnu
```

**Comment by geimer** [comment]
@boegel: Yep, noticed that already ;-)  With the `-L` it seems to work well.

There is no `/usr/lib64` on a 64-bit Debian multiarch system.  64-bit libraries are in `/usr/lib/x86_64-linux-gnu`, 32-bit libs in `/usr/lib/i386-linux-gnu`.  However, I don't think we have to care much about the 32-bit stuff as all available easyconfigs only install a 64-bit compiler which cannot produce 32-bit code:
```
$ pgcc -m32 -o hello hello.c 
pgcc-Fatal--m32 is not supported in this installation
```

**Comment by boegel** [comment]
@geimer: OK, added, thanks!

Should be good to go now?

**Comment by geimer** [comment]
@boegel: Reinstalled PGI with this PR applied and it works for me, so in that sense it's good to go.  But do you want to include this directory unconditionally?  Should be OK, but maybe someone with a non-Debian system should verify that it doesn't break anything?

**Comment by boegel** [comment]
@geimer: I checked that with `pgcc -v hello.c`; works fine, path is not mentioned in that output, so seems like PGI checks for existence itself.

Going in, thanks for the feedback @damianam, @rjeschmi and @geimer!

**Pull request merged**
