### PR TITLE
change suffix of original file to .easybuild when using fileinput in impi easyblock

### PR DESCRIPTION
**Pull request by ocaisa**
The .eb extension is a bad choice because it actually means something

### CODE REVIEW

**Comment by ocaisa** [comment]
This messes up scripts I have that automatically pull easyconfigs from existing installations

**Comment by boegel** [comment]
@ocaisa looks ok to include, but your script shouldn't be picked up `.eb` files from random locations?

**Comment by ocaisa** [comment]
I never said it was my script...

**Comment by boegel** [comment]
going in, thanks @ocaisa

**Pull request merged**
