### PR TITLE
fix extension filter for Ruby, drop deprecated 'testrb' from sanity check

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@rjeschmi please review?

**Comment by rjeschmi** [comment]
looks fine. Was there any problem with the previous extensions check (ie did it miss somethign?)

**Comment by boegel** [comment]
@rjeschmi apparently the argument is a regex, I ran into false positives with short names like `gh` (see also https://github.com/hpcugent/easybuild-easyconfigs/pull/2953)

**Comment by boegel** [comment]
Tested with https://github.com/hpcugent/easybuild-easyconfigs/pull/2953, good to go.

Thanks for the review @rjeschmi!

**Comment by rjeschmi** [comment]
Good catch.

**Pull request merged**
