### PR TITLE
160101 dylib dev: Some fixes for Macintosh

### PR DESCRIPTION
**Pull request by citibob**
(see issue #787)

More to come later, if the EasyBuild team determines these changes are headed in the right direction.

### CODE REVIEW

**Comment by citibob** [comment]
Yes

**Comment by boegel** [comment]
@citibob: thanks for this contribution! Aside from some minor style remarks, it looks good.

But, please always target the `develop` branch when opening pull requests; the only time when a PR to `master` gets merged is when a new EasyBuild version is released.

Changing the target branch for a pull request is not possible, so please open a new pull request and close this one. We can make style suggestions in the other PR, and I can make sure our bot tests your pull request.

**Comment by citibob** [comment]
Kenneth,

OK, I think I found what was wrong and re-submitted.

The original branch I made (160101-Dylib) was off of the master branch.
But then I dutifully rebased it to develop to create 160101-Dylib-dev. I
thought I was done.

 BUT NO... it looks like when I make a pull request, I have to AGAIN
specify I want it based on develop, not master.

Please see how that goes.

-- Elizabeth

**Comment by boegel** [comment]
@citibob: the branch you start from and the one you target when opening a pull request are typically the same (should be `develop` in this case), but it doesn't have to be, so yes, when opening a pull request you need to specify that you want to merge the change to `develop`

Your new PR #789 does exactly that, so let's follow up there and close this one.

**Pull request closed without merging**
