### PR TITLE
Cp2k 3.0 Cray support

### PR DESCRIPTION
**Pull request by gppezzi**
Same as for boost, this is a tweaked version of cp2k.py.

by @lucamar

### CODE REVIEW

**Comment by boegel** [comment]
Same remark as for Boost: this should be reworked to reuse the efforts in `cp2k.py`, rather than copy-paste; this is a maintenance nightmare as is...

**Comment by gppezzi** [comment]
I just did the diff, we're actually just adding CUDA support:
```
         # CUDA
         cuda = get_software_root('CUDA')
         if cuda:
             options['DFLAGS'] += ' -D__ACC -D__DBCSR_ACC'
             options['LIBS'] += ' -lcudart -lcublas -lcufft -lrt'
             options['NVCC'] = ' nvcc'
```
It looks like harmless to add this to the existing cp2k easyblock, what do you say ?

**Comment by boegel** [comment]
Looks reasonable, yeah.

Can you update this PR to actually make it modify the existing `cp2k.py`?

```
cp easybuild/easyblocks/c/cp2kcray.py easybuild/easyblocks/c/cp2k.py
git rm easybuild/easyblocks/c/cp2kcray.py
git commit -a -m "..."
...
```

**Comment by gppezzi** [comment]
@boegel cuda support is integrated into the existing easyblock, can you please review?

@lucamar any remarks?

**Comment by boegel** [comment]
lgtm, thanks @gppezzi and @lucamar!

**Comment by boegel** [comment]
Tested a couple of CP2K builds on top of this, (still) working fine, so good to go.

**Pull request merged**
