### PR TITLE
impi mic mpivars fix

### PR DESCRIPTION
**Pull request by stachon**
the bash version was incorrect

### CODE REVIEW

**Comment by stachon** [comment]
Yes

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by boegel** [comment]
@stachon: fix looks good, but pull requests should target the `develop` branch, `master` is only updated on new releases (typically one big PR from `develop` to `master`)

See https://github.com/hpcugent/easybuild/wiki/Contributing-back for a detailed overview.

Can you look into issuing a new PR that targets our `develop` branch?

If it's too much of a hassle, I can do it for you (but since it's your contribution, it would be nicer if you do it yourself).

I really want to include this in EasyBuild v2.2.1, to be released very soon (early next week, probably).

**Comment by stachon** [comment]
@boegel Hi, sorry about that, I have created a new pull requested #662, hope it is OK now.

**Comment by boegel** [comment]
no worries, let close this and handle it via #662, looks good

**Pull request closed without merging**
