### PR TITLE
Use correct configure option for checkpoint/restart in MVAPICH2 easyblock

### PR DESCRIPTION
**Pull request by besserox**
MVAPICH2 easyblock uses the wrong configure options to enable the checkpoint/restart support. It uses the options from MPICH instead of the one from MVAPICH2. As a result, I'm pretty sure that the checkpoint/restart is not working properly with this build.

The issue with this change is that the result of the build will be different. However, this affect only one easyconfig file `MVAPICH2-1.7-GCC-4.6.3-hwloc-chkpt.eb`. 

For reference:
- Checkpoint/Restart support in MVAPICH2:
http://mvapich.cse.ohio-state.edu/static/media/mvapich/mvapich2-2.2b-userguide.html#x1-120004.4
- Checkpoint/Restart support in MPICH:
https://wiki.mpich.org/mpich/index.php/Checkpointing

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

**Comment by besserox** [comment]
@boegel This PR is independent of my other MVAPICH2-related PRs. 

Any thought about it?

**Comment by boegel** [comment]
@besserox is there any way to check whether the checkpointing support is working or not?

Don't worry about this changing the build, this is a bug fix, so we're changing the build for good reasons.

We don't need to maintain backward compatibility with doing it wrong in the past... ;)

**Comment by besserox** [comment]
@boegel As far I know there is nothing to test the checkpoint support. Probably the best thing would be to run a MPI application, checkpoint it, and restart it. But that's a bit of a heavy process for EasyBuild. That's more something for my MPI stack testing tool (https://github.com/besserox/ATIS/tree/master/MPI), but it's a dead project for now.

**Comment by boegel** [comment]
@besserox Maybe with `ldd libmpich.so`, which may show that `libcr.so` is linked?

In any case: your fix is triggering something alright, the build of the one MVAPICH easyconfig that is supposed to enable checkpointing is now failing with:

```
cr.c:29:24: fatal error: attr/xattr.h: No such file or directory
compilation terminated.
make[8]: *** [cr.o] Error 1
```

Does it work on your end? Any idea what's going on?

**Comment by besserox** [comment]
@boegel  

- About the test, I remember that MVAPICH2 installs an additional executable `mv2_checkpoint` when checkpoint/restart is enabled. I have added this check.

  We can also check if `libmpich.so` and/so `mpirun_rsh` are linked to `libcr.so` as you suggested. 
  What would be the proper way to do an `ldd mpirun_rsh | grep libcr.so` in Python?

- About the compilation error you reported. I have updated the `osdependencies` in the easyconfig in PR https://github.com/hpcugent/easybuild-easyconfigs/pull/2699

**Comment by boegel** [comment]
@besserox just checking for `mv2_checkpoint` is good enough for me

Tested with https://github.com/hpcugent/easybuild-easyconfigs/pull/2699, good to go, thanks!

**Pull request merged**
