### PR TITLE
include update statements for $CPATH and $*LIBRARY_PATH in generated module in numpy easyblock

### PR DESCRIPTION
**Pull request by boegel**
requires https://github.com/hpcugent/easybuild-framework/pull/2229

### CODE REVIEW

**Comment by akesandgren** [comment]
I get:
AttributeError: 'EB_numpy' object has no attribute 'module_generator'

Did i make an error when hand editing my numpy.py or?

**Comment by boegel** [comment]
@akesandgren You also need the change in ake_s: yes, you need this one line change in framework too: https://github.com/hpcugent/easybuild-framework/pull/2229/files#diff-1b202be69819e7f06f809e80c73f7789R87

**Comment by akesandgren** [comment]
Works, produces the needed CPATH/*LIBRARY_PATH extensinos.

**Comment by akesandgren** [comment]
And GPAW 0.11 builds with it (and there is no python-numpy from the OS this time)

**Comment by akesandgren** [comment]
I.e., works for me.

**Comment by boegel** [comment]
Thanks for the review @wpoely86 and @akesandgren for testing this!

**Pull request merged**
