### PR TITLE
Updated qe

### PR DESCRIPTION
**Pull request by damianam**
This fixes https://github.com/hpcugent/easybuild-easyblocks/issues/903

### CODE REVIEW

**Comment by boegel** [comment]
Jenkins: ok to test

hmmm, why isn't Travis testing this :(

**Comment by boegel** [comment]
@damianam the close/open was to try and trigger Travis...

**Comment by damianam** [comment]
Seems like Travis is a dirty slacker.

**Comment by boegel** [comment]
well, no, see https://travis-ci.org/hpcugent/easybuild-easyblocks/builds/126174122

it's just that the commit is not being marked successful for some reason... :-/

**Comment by boegel** [comment]
going in, thanks @damianan

note that there's no need to create an issue first if you're going to submit a PR, that only results in overhead...

**Pull request merged**
