### PR TITLE
also consider setuptools in EasyBuildMeta easyblock

### PR DESCRIPTION
**Pull request by boegel**
also consider `setuptools` in case it is listed as one of the sources in the `EasyBuild` easyconfig file

This is required to work around the problem reported in #1090

### CODE REVIEW

**Comment by damianam** [comment]
@boegel I find it confusing that you add packages in `__init__`, even if they aren't included as sources, and then, if they are not in the sources, just ignore them. Wouldn't it be more clear (and cleaner) if `setuptools` (and possibly `vsc-install` and `vsc-base`, but I don't fully understand why you need them twice) is added to `easybuild_pkgs` if, and just if, it is listed in `self.src`?

**Comment by boegel** [comment]
@damianam I guess we could do that too, yeah. Do you want me to make that change now though? I'd like to avoid spending too much time on this now... Making changes to the `EasyBuildMeta` easyblock is a bit tricky, since it also affects the bootstrap script, etc.

W.r.t. `vsc-base` and `vsc-install`: this is only because those may be picked up from the OS, if a more recent `vsc-base` or `vsc-install` is available there. That mostly a concern for HPC-UGent/VSC systems, other systems most likely don't have these installed system-wide.

**Comment by damianam** [comment]
@boegel: "jain". Doing it now or later I think it doesn't matter. But I think it should be done. To fix https://github.com/hpcugent/easybuild-easyblocks/issues/1090 and don't delay `3.1.0`, I guess you can keep it as it is now, after all it doesn't affect the functionality, but open an issue with target `3.1.1` or `3.2.0` to don't forget about it later.

**Comment by boegel** [comment]
@damianam issue opened at https://github.com/hpcugent/easybuild-easyblocks/issues/1095, thanks for the review!

**Pull request merged**
