### PR TITLE
Updated go easyblock for version 1.5. This version need the variable …

### PR DESCRIPTION
**Pull request by cfenoy**
…GOROOT_BOOTSTRAP to point to a current Go installation

### CODE REVIEW

**Comment by boegel** [comment]
@cfenoy: please target the `develop` branch for making changes; `master` is the 'stable' version, and is only updated when a new EB release is made (by merging `develop` into `master` after running regression tests)

You'll need to issue a new PR since you can't change the target branch for an open PR.

**Comment by boegel** [comment]
@cfenoy: see also https://github.com/hpcugent/easybuild/wiki/Contributing-back and https://github.com/hpcugent/easybuild/wiki/Policy-for-easyconfig-pull-requests (latter are just guidelines, we're not strictly enforcing those things)

**Comment by cfenoy** [comment]
@boegel Sorry for that, I'll create a new PR

**Comment by boegel** [comment]
@cfenoy: no problem, it's a common 'mistake' for people issuing PRs to EB repos for the first time

we want to keep `master` as the default branch since that's what people should be playing with when they clone the repo, but that implies it's also the default target for PRs...

**Pull request closed without merging**
