### PR TITLE
fix setting of $INTEL_LICENSE_FILE for port@server values

### PR DESCRIPTION
**Pull request by boegel**
fix for #608

requires https://github.com/hpcugent/easybuild-framework/pull/1310

cc @akesandgren

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 or @JensTimmerman: please review?

**Comment by boegel** [comment]
(note: unit tests fail because https://github.com/hpcugent/easybuild-framework/pull/1310 is missing, but please do review)

**Comment by wpoely86** [comment]
looks good

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
