### PR TITLE
use apply_regex_substitutions in WRF easyblock

### PR DESCRIPTION
**Pull request by boegel**
requires ~~https://github.com/hpcugent/easybuild-framework/pull/1388~~ and https://github.com/hpcugent/easybuild-framework/pull/1458

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: thoughts before I flesh this out (and test the changes)?

This is sort of required to make the output of `eb -x` more usable (see https://github.com/hpcugent/easybuild-framework/pull/1388), i.e. it enables us mocking the patching rather that ignoring the error `fileinput` generates

**Comment by wpoely86** [comment]
Looks fine I guess?

**Comment by boegel** [comment]
@wpoely86: that sounds very convincing... :P

**Comment by wpoely86** [comment]
Well, I see no problems but the proof of the pudding is in the eating...

**Comment by boegel** [comment]
Yeah, this will need to be tested thoroughly, of course.

But I'll focus on getting https://github.com/hpcugent/easybuild-framework/pull/1388 merged first.

These changes are not strictly required to make `eb -x` work, but they do result in more useful output (i.e., no errors being ignored/reported, which hide part of the step where they occur).

**Comment by boegel** [comment]
checked the WRF build on top of https://github.com/hpcugent/easybuild-framework/pull/1458, works as it should, so this is good to go when https://github.com/hpcugent/easybuild-framework/pull/1458 is merged in

Thanks for the review @wpoely86!

**Pull request merged**
