### PR TITLE
make PythonPackage easyblock compatible with --module-only

### PR DESCRIPTION
**Pull request by boegel**
When using `--module-only`, the `configure_step` is skipped, resulting in `self.python_cmd` not being defined.

This leads to an error like:

```
== temporary log file in case of crash /tmp/eb-D0fij6/easybuild-zoU8DE.log
== processing EasyBuild easyconfig /vscmnt/gent_vulpix/_/user/data/gent/gvo000/gvo00002/vsc40023/wxPython-3.0.2.0-intel-2016-Python-2.7.11.eb
== building and installing wxPython/3.0.2.0-intel-2016a-Python-2.7.11...
== fetching files [skipped]
== creating build dir, resetting environment...
== unpacking [skipped]
== patching [skipped]
== preparing...
== configuring [skipped]
== building [skipped]
== testing [skipped]
== installing [skipped]
== taking care of extensions [skipped]
== postprocessing [skipped]
== sanity checking...
ERROR: Traceback (most recent call last):
  File "/user/scratchdelcatty/gent/gvo000/gvo00002/vsc40023/easybuild_easy_installed/lib/python2.6/site-packages/easybuild_framework-2.8.0dev0-py2.6.egg/easybuild/main.py", line 113
, in build_and_install_software                                                                                                                                                      
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_easy_installed/lib/python2.6/site-packages/easybuild_framework-2.8.0dev0-py2.6.egg/easybuild/framework/easyblock.py", line 2292,
 in build_and_install_one                                                                                                                                                            
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_easy_installed/lib/python2.6/site-packages/easybuild_framework-2.8.0dev0-py2.6.egg/easybuild/framework/easyblock.py", line 2208,
 in run_all_steps                                                                                                                                                                    
    self.run_step(step_name, step_methods)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_easy_installed/lib/python2.6/site-packages/easybuild_framework-2.8.0dev0-py2.6.egg/easybuild/framework/easyblock.py", line 2087,
 in run_step                                                                                                                                                                         
    step_method(self)()
  File "/tmp/eb-D0fij6/included-easyblocks/easybuild/easyblocks/wxpython.py", line 64, in sanity_check_step
    super(EB_wxPython, self).sanity_check_step(custom_paths=custom_paths)
  File "/user/scratch/gent/vsc400/vsc40023/easybuild_easy_installed/lib/python2.6/site-packages/easybuild_easyblocks-2.8.0dev0-py2.6.egg/easybuild/easyblocks/generic/pythonpackage.p
y", line 471, in sanity_check_step                                                                                                                                                   
    exts_filter = (orig_exts_filter[0].replace('python', self.python_cmd), orig_exts_filter[1])
TypeError: expected a character buffer object
```

This patch fixes the issue.

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86 please review

**Comment by wpoely86** [comment]
:+1:

**Comment by boegel** [comment]
(open/close to trigger Travis testing this too, apparently that's one of the go-to ways... :-/)

**Comment by boegel** [comment]
updated PR was tested by Travis (cfr. https://travis-ci.org/hpcugent/easybuild-easyblocks/builds/126192549), but 'notification' is not making it back for some reason...

anyway, going in :)

**Pull request merged**
