### PR TITLE
bump version to 2.1.0 and update release notes

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by fgeorgatos** [comment]
looks good to me

**Comment by boegel** [comment]
Thanks for the review!

I'll merge this in, fork off a version branch, and bump the version in develop to `2.2.0dev`; release will happen later.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
going in, thanks for the review @fgeorgatos!

**Pull request merged**
