### PR TITLE
prepend tmp install path to $PYTHONPATH in numpy test step

### PR DESCRIPTION
**Pull request by boegel**
The `$PYTHONPATH` should have included the temporary install location all along, but this was not a problem up until now because numpy was still using `distutils`; with numpy 1.11, they switched to using `setuptools`, which means you run into this problem during the numpy test step:

```
running install
Checking .pth file support in <numpy_install_prefix>
/user/scratch/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.11-intel-2016a/bin/python -E -c pass
TEST FAILED: /local/2297564[2861].master15.delcatty.gent.vsc/eb-cVBudI/tmpmFHiMz/lib/python2.7/site-packages does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.
...
```

This should fix the issue reported by @damianam in https://github.com/hpcugent/easybuild-easyconfigs/pull/2861

### CODE REVIEW

**Comment by wpoely86** [comment]
:+1:

**Comment by damianam** [comment]
It doesn't seem to work for me:

```
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/tmp/eb-FOQRT9/tmpB0cj8A/lib/python2.7/site-packages/test-easy-install-16107.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /tmp/eb-FOQRT9/tmpB0cj8A/lib/python2.7/site-packages

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
```

Unfortunately I don't have the time now to look deeply into it.

**Comment by boegel** [comment]
@damianam The problem was that the `site-packages` in the subdirectory needs to *exist* too, fixed now, please retest?

**Comment by boegel** [comment]
tested with https://github.com/hpcugent/easybuild-easyconfigs/pull/2861, so looks good to me now...

please confirm @damianam?

**Comment by boegel** [comment]
@damianam the last commit (6149478) solves the `No such file or directory` issue you ran into when numpy is the last extension listed in `exts_list`, please verify?

**Comment by damianam** [comment]
Consider it verified :-)

**Comment by boegel** [comment]
Thanks for the confirmation @damianam, going in!

**Pull request merged**
