### PR TITLE
don't hardcode 'openPBS' in GATE easyblock, use value for default_platform easyconfig parameter

### PR DESCRIPTION
**Pull request by boegel**
cfr. https://github.com/hpcugent/easybuild-easyconfigs/issues/2156

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: please review?

**Comment by wpoely86** [comment]
looks good

**Comment by boegel** [comment]
Jenkins: test this pleae

**Comment by boegel** [comment]
Thanks for the review @wpoely86!

**Pull request merged**
