### PR TITLE
check for libkokkoscore.a rather than libkokkos.a for Trilinos 12.x

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by rjeschmi** [comment]
Looks good

**Comment by boegel** [comment]
I'm still testing this, but I'm pretty confident it'll work. I'll merge it once I have confirmation.

**Comment by boegel** [comment]
Thanks for the review @rjeschmi!

**Comment by boegel** [comment]
tested with the updates Trilinos 12.4.2 easyconfig from https://github.com/hpcugent/easybuild-easyconfigs/pull/2271, works as intended, so going in

Thanks for the review @rjeschmi!

**Pull request merged**
