### PR TITLE
define $NWCHEM_LONG_PATH if needed

### PR DESCRIPTION
**Pull request by boegel**
cfr. https://github.com/hpcugent/easybuild-easyconfigs/pull/2069#issuecomment-149800162

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato: please review?

**Comment by hajgato** [comment]
@boegel Its perfect.

**Comment by boegel** [comment]
@hajgato: it would be even more perfect if it actually worked (see https://github.com/hpcugent/easybuild-easyconfigs/pull/2069#issuecomment-149816618)... O_o

**Comment by boegel** [comment]
Ah, there's a hard check on `Y`:

```
ifeq ($(NWCHEM_LONG_PATHS),Y)
```

So, using `TRUE` as a value won't work. Will fix.

**Comment by boegel** [comment]
@hajgato (or @wpoely86?): please (re)review?

**Comment by wpoely86** [comment]
lgtm

**Comment by hajgato** [comment]
@boegel; w8

**Comment by hajgato** [comment]
@boegel Should we change this to `write_file` as well?
https://github.com/hpcugent/easybuild-easyblocks/pull/720/files#diff-b41a4d16528ca26f79b921312c12c018L320

**Comment by boegel** [comment]
@hajgato: will do?

**Comment by hajgato** [comment]
:)

**Comment by boegel** [comment]
Tested via https://github.com/hpcugent/easybuild-easyconfigs/pull/2069, working as expected.

Thanks for the review @hajgato and @wpoely86!

**Pull request merged**
