### PR TITLE
add generic easyblock ConfigureMakePythonPackage

### PR DESCRIPTION
**Pull request by boegel**
cleaned up version of #533 by @Bart-CER, mostly style fixes

### CODE REVIEW

**Comment by boegel** [comment]
@wpoely86: any remarks on this one?

**Comment by wpoely86** [comment]
no. looks good to me. 

But are there really that many package out there that use this kind of build system?

**Comment by boegel** [comment]
Two is enough, who knows what others may pop up: https://github.com/hpcugent/easybuild-easyconfigs/pull/1349

**Comment by Bart-CER** [comment]
@boegel Sorry, didn't realise you changed 2 files in the generic blocks. It's working perfectly now.

**Comment by boegel** [comment]
Jenkins: test this please

**Comment by boegel** [comment]
Well tested with https://github.com/hpcugent/easybuild-easyconfigs/pull/1322, looks good, so going in.

Thanks for looking into this @Bart-CER!

**Pull request merged**
