### PR TITLE
xorg (WIP)

### PR DESCRIPTION
**Pull request by hajgato**
Maybe not the best solution, a bit slow, because unpacking and patching happens multiple times.
Additionally, the corresponding easyconfig finishes with:
```
== packaging...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/hajgato/build/Xorgheadres/20160225/intel-2016a): (no error)
== Results of the build can be found in the log file /tmp/hajgato/eb-gaE9VH/easybuild-Xorg-headres-20160225-20160226.232539.rCjMe.log
```
And I do not know the reason (the easybuild log is missing in the software directory)

### CODE REVIEW

**Comment by boegel** [comment]
@hajgato: did you check the log file in `/tmp` (see also the output you pasted) for what may be going wrong in the `package` step?

**Comment by boegel** [comment]
hmm, lot's of copy-pasting going on here... :(

@hajgato: do you have an example easyconfig?

**Comment by hajgato** [comment]
@boegel less copypasting with previous commit (https://github.com/hajgato/easybuild-easyblocks/commit/b61424dbd3dd3e6e238d0cc5b3cc113c722d363a) But then every loop there is an unpack, patch cycle, and we do need it only once. I am open to everything, if you say so that's not a problem, then it is fine for me.

**Comment by hajgato** [comment]
@boegel: Check the easyconfig: https://github.com/hpcugent/easybuild-easyconfigs/issues/2579

**Comment by hajgato** [comment]
@boegel I have checked the `/tmp` logfile, and I still do not see anything:
```
== 2016-02-27 12:23:54,351 not available in optimized mode.EB_Xorg INFO packaging...
== 2016-02-27 12:23:54,351 not available in optimized mode.EB_Xorg INFO Starting package step
== 2016-02-27 12:23:54,354 not available in optimized mode.EB_Xorg INFO Running method package_step part of step package
== 2016-02-27 12:23:54,354 not available in optimized mode.EB_Xorg INFO Skipping package step (not enabled)
== 2016-02-27 12:23:54,354 not available in optimized mode.EB_Xorg INFO Closing log for application name Xorg-headers version 20160225
== 2016-02-27 12:23:54,354 not available in optimized mode.EB_Xorg INFO Closing log for application name Xorg-headers version 20160225
== 2016-02-27 12:23:54,355 not available in optimized mode.easyblock INFO FAILED: Installation ended unsuccessfully (build directory: /tmp/hajgato/build/Xorgheaders/20160225/intel-2016a): (no error)
== 2016-02-27 12:23:54,355 not available in optimized mode.easyblock INFO Results of the build can be found in the log file /tmp/hajgato/eb-_jhLpF/easybuild-Xorg-headers-20160225-20160227.121914.OeQAX.log
== 2016-02-27 12:23:54,432 not available in optimized mode ERROR (no error) (at easybuild/main.py:116 in build_and_install_software)
== 2016-02-27 12:23:54,433 not available in optimized mode ERROR Build of /vsc/apps/brussel/easybuild_develop/easybuild-easyconfigs/easybuild/easyconfigs/x/Xorg-headers/Xorg-headers-20160225-intel-2016a.eb failed (err: '(no error)') (at easybuild/main.py:148 in build_and_install_software)
```

**Comment by ocaisa** [comment]
Leveraging [jhbuild](https://www.x.org/wiki/JhBuildInstructions/) might be a good way of avoiding some pain with X (I'v only been reading about though, I have no real experience)

**Comment by hajgato** [comment]
A better solution (extension of `Bundle` EasyBlock) is available in PR #980

**Pull request closed without merging**
