### PR TITLE
Easyblock for pbdMPI R package

### PR DESCRIPTION
**Pull request by pm67nz**

### CODE REVIEW

**Comment by boegel** [comment]
@pm67nz: duplicate of #620, which seems to take a better approach (i.e. via `configure_step`, recognize more MPI types, only specify required `--with-mpi-type` since rest is derived correctly from enviroment)?

@ehiggs: thoughts?

**Comment by ehiggs** [comment]
This is a good version. My PR also has pbdSLAP. Maybe merge mine and then push this on top?

**Comment by boegel** [comment]
I collapsed this into #620, so this PR will be included once #620 is merged into develop.

**Comment by boegel** [comment]
merged via #620

**Pull request merged**
