### PR TITLE
numpy: test whether self.patches is None (with mkl)

### PR DESCRIPTION
**Pull request by thiell**
Patch proposal for issue #716.

### CODE REVIEW

**Comment by boegel** [comment]
@thiell: although this will fix the problem for numpy, the problem actually lies higher up, in the EasyBuild framework, i.e. here:

```
$ sed -n "60,61p" easybuild/framework/extension.py
        self.src = self.ext.get('src', None)
        self.patches = self.ext.get('patches', None)
```

The fallback value `None` used above doesn't correspond with the default `[]` value for `self.patches` and `self.src` at:

```
$ sed -n "138,139p" easybuild/framework/easyblock.py
        self.patches = []
        self.src = []

```

So, the fix should be made in `easybuild/framework/extension.py` instead, since this problem is not specific to the numpy easyblock.

Are you up for looking into that?

**Comment by thiell** [comment]
@boegel: ok thx for looking, I understand, I will look at it ASAP and submit another pull request (to easybuild-framework).

**Comment by boegel** [comment]
@thiell: let's close this one since https://github.com/hpcugent/easybuild-framework/issues/1434 provides a better solution?

**Comment by thiell** [comment]
@boegel: sure, let's close it, thx!

**Pull request closed without merging**
