### PR TITLE
adding pgi easyblock for issues/808

### PR DESCRIPTION
**Pull request by jgphpc**
https://github.com/hpcugent/easybuild-easyblocks/issues/808

### CODE REVIEW

**Comment by boegel** [comment]
@jgphpc: please sync with current develop, now that #658 is merged?

**Comment by boegel** [comment]
@jgphpc: ping?

**Comment by boegel** [comment]
@jgphpc as far as I can tell, everything in this PR is already merged elsewhere, so this can be closed?

**Comment by jgphpc** [comment]
> @jgphpc as far as I can tell, everything in this PR is already merged elsewhere, so this can be closed?
give me +30 minutes to test it

**Comment by jgphpc** [comment]
jgphpc:808_craypgi is a duplicate of https://github.com/hpcugent/easybuild-easyblocks/pull/658/files
How can i delete my branch ?

**Comment by boegel** [comment]
@jghpc To delete a branch in your fork, use `git push origin :<branch_name>`, assuming `origin` points to *your* fork (check with `git remote -v`)

So, like this (or similar):

```
git push origin :808_craypgi
```

The `:` indicates to delete the branch. Be careful when doing that, unless you have local copy, you may lose work (although for your `808_craypgi` branch it should be fine).

Please make sure you close this PR too (although removing the branch should result in this PR being closed automagically).

**Pull request closed without merging**
